<?php
if (function_exists("acf_add_local_field_group")):
  acf_add_local_field_group([
    "key" => "group_5d08f2f81c66d",
    "title" => "Elasticsearch settings",
    "fields" => [
      [
        "key" => "field_5d08f56d7691c",
        "label" => "Indexerade posttyper",
        "name" => "indexed_post_types",
        "type" => "posttype_select",
        "instructions" =>
          'OBS! Uppdatering kräver en sync av elasticpress indexet. <a href="/wp/wp-admin/admin.php?page=elasticpress">Sida för synkronisering</a>',
        "required" => 1,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "80",
          "class" => "",
          "id" => "",
        ],
        "default_value" => "",
        "allow_null" => 0,
        "multiple" => 1,
        "placeholder" => "",
        "disabled" => 0,
        "readonly" => 0,
      ],
      [
        "key" => "field_5d08f56d4690a",
        "label" => "Indexera posttypernas arkiv",
        "name" => "indexed_post_type_archives",
        "type" => "true_false",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "20",
          "class" => "",
          "id" => "",
        ],
        "default_value" => 1,
        "message" => "",
        "ui" => 1,
        "ui_on_text" => "Ja",
        "ui_off_text" => "Nej",
      ],
      [
        "key" => "field_5d08f4ef7691b",
        "label" => "Exkludera post från sök",
        "name" => "exclude_post_from_index",
        "type" => "post_object",
        "instructions" =>
          'OBS! Uppdatering kräver en sync av elasticpress indexet. <a href="/wp/wp-admin/admin.php?page=elasticpress">Sida för synkronisering</a>',
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "post_type" => [],
        "taxonomy" => [],
        "allow_null" => 1,
        "multiple" => 1,
        "return_format" => "id",
        "ui" => 1,
      ],
      [
        "key" => "field_5ec52667d46f6",
        "label" => "Välj index",
        "name" => "query_indices",
        "type" => "select",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "default_value" => [],
        "allow_null" => 1,
        "multiple" => 1,
        "placeholder" => "",
        "disabled" => 0,
        "readonly" => 0,
        "choices" => [],
        "ui" => 0,
        "ajax" => 0,
        "return_format" => "value",
      ],
      [
        "key" => "field_5d08f3977691a",
        "label" => "Boosta posttyp",
        "name" => "boost_post_type",
        "type" => "posttype_select",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "default_value" => "",
        "allow_null" => 1,
        "multiple" => 1,
        "placeholder" => "",
        "disabled" => 0,
        "readonly" => 0,
      ],
      [
        "key" => "field_5d137a554828b",
        "label" => "Minsta poäng för relevans",
        "name" => "ws_ep_min_score",
        "type" => "number",
        "instructions" =>
          "Kontrollera gränsen för vilka resultat som anses relevanta. Värdet går att expirementera för men gäller globalt för alla sökord. Det går att skriva med decimaler ex. 2,7",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "default_value" => 2,
        "placeholder" => "",
        "prepend" => "",
        "append" => "",
        "min" => 0,
        "max" => 50,
        "step" => "0.1",
      ],
      [
        "key" => "field_5d08e65a46bf0",
        "label" => "Alla Synonymer",
        "name" => "municipio_elasticpress_synonyms",
        "type" => "repeater",
        "instructions" =>
          'OBS! Uppdatering kräver en sync av elasticpress indexet. <a href="/wp/wp-admin/admin.php?page=elasticpress">Sida för synkronisering</a>',
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "collapsed" => "",
        "min" => 0,
        "max" => 0,
        "layout" => "block",
        "button_label" => "Map a new synonym",
        "sub_fields" => [
          [
            "key" => "field_5d08e67046bf1",
            "label" => "En Synonym",
            "name" => "one_synonym",
            "type" => "repeater",
            "instructions" =>
              "Skapa en lista av synonymer för gemensamma ord. Ordningen spelar ingen roll. Alla ord kommer att motsvara varandra och bli sökbara",
            "required" => 0,
            "conditional_logic" => 0,
            "wrapper" => [
              "width" => "",
              "class" => "",
              "id" => "",
            ],
            "collapsed" => "",
            "min" => 2,
            "max" => 0,
            "layout" => "table",
            "button_label" => "Add a new synonym",
            "sub_fields" => [
              [
                "key" => "field_5d08e6ae46bf2",
                "label" => "Synonym",
                "name" => "synonym",
                "type" => "text",
                "instructions" =>
                  "Endast 1 ord. Undvik specialtecken och mellanslag",
                "required" => 1,
                "conditional_logic" => 0,
                "wrapper" => [
                  "width" => "",
                  "class" => "",
                  "id" => "",
                ],
                "default_value" => "",
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
                "maxlength" => "",
              ],
            ],
          ],
        ],
      ],
      [
        "key" => "field_5fd728fb9a045",
        "label" => "Sökordsförslag",
        "name" => "municipio_elasticsearch_suggestions",
        "type" => "textarea",
        "instructions" => "Ange sökordsförslag, ett per rad.",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "default_value" => "",
        "placeholder" => "",
        "maxlength" => "",
        "rows" => "",
        "new_lines" => "",
      ],
    ],
    "location" => [
      [
        [
          "param" => "options_page",
          "operator" => "==",
          "value" => "acf-options-search",
        ],
      ],
    ],
    "menu_order" => 0,
    "position" => "normal",
    "style" => "default",
    "label_placement" => "top",
    "instruction_placement" => "label",
    "hide_on_screen" => "",
    "active" => true,
    "description" => "",
  ]);
endif;
